= Preparation
== Overview
== Input formats
== Identifiers
== Basic parsing

These operations are done on all terms:

1. Leading or trailing whitespace is removed.
2. Tabs and newlines are converted to spaces.
3. The exact value `null`, `\N`, `''` or `""` is removed

== Controlled vocabularies
== Taxonomy
== Date/Time
== Location
=== Interpretation

--
Darwin Core Terms: country, countryCode, decimalLatitude, decimalLongitude, geodeticDatum, coordinateUncertaintyInMeters, coordinatePrecision, verbatimCoordinates, verbatimLatitude, verbatimLongitude, verbatimCoordinateSystem, verbatimSRS
--

==== Interpret the datum

Parse the `geodeticDatum` using ####.  If it fails or is unspecified, add issues ###.

==== Interpret the coordinatePrecision

This records a value in degrees.  The value should be in the range 0–1°, otherwise add an issue ###.

==== Interpret the coordinateUncertaintyInMeters

This should be a number greater than zero (not equal to zero), less than (half the Earth's circumference).  It should also be greater than the precision calculated by https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#uncertainty-related-to-coordinate-precision, and greater than the uncertainty introduced by an unknown datum https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#uncertainty-from-unknown-datum

==== Interpret the country

Use the uncertainty from above.

=== Grids
==== UTM
=== Political boundaries (GADM.org)
=== Habitats
=== Protected areas
=== Environmental layers
=== Sensitive data
=== Outlier detection
== Fitness for use
== Invasive species
== Traits
== Multimedia
== Sequences
== Outlier detection
== Data quality flags
